spring.application.name=citas-service

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:patitas_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:patitas_pass}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect